//Justin Anderson - May 2012
//Compile: gcc TesterBot.c libcAI.so -o TesterBot
//Run: ./TesterBot
#include "cAI.h"
#include <stdio.h>
#define PI 3.1415926536
AI_loop() {
    //turnLeft(1);
    //turnRight(1);
    //turn(20);
    //turnToDeg(270);
    //thrust(1);
    //setTurnSpeed(1);
    //setPower(1);
    //fasterTurnrate();
    //slowerTurnrate();
    //morePower();
    //lessPower();
    //fireShot();
    //fireMissile();
    //fireTorpedo();
    //fireHeat();
    //dropMine();
    //detachMine();
    //detonateMines();
    //fireLaser();
    //tankDetach();
    //cloak();
    //ecm();
    //transporter();
    //tractorBeam(1);
    //pressorBeam(1);
    //phasing();
    //shield();
    //emergencyShield();
    //hyperjump();
    //nextTank();
    //prevTank();
    //toggleAutopilot();
    //emergencyThrust();
    //deflector();
    //selectItem();
    //loseItem();
    //lockNext();
    //lockPrev();
    //lockClose();
    //lockNextClose();
    //loadLock1();
    //loadLock2();
    //loadLock3();
    //loadLock4();
    //toggleNuclear();
    //togglePower();
    //toggleVelocity();
    //toggleCluster();
    //toggleMini();
    //toggleSpread();
    //toggleLaser();
    //toggleImplosion();
    //toggleUserName();
    //loadModifiers1();
    //loadModifiers2();
    //loadModifiers3();
    //loadModifiers4();
    //clearModifiers();
    //connector(1);
    //dropBall();
    //refuel(1);
    //keyHome();
    //selfDestruct();
    //pauseAI();
    //swapSettings();
    //quitAI();
    //talkKey();
    //toggleCompass();
    //toggleShowMessage();
    //toggleShowItems();
    //repair();
    //reprogram();
    //talk("Hello");
    //printf("scanMsg: %s \n",scanMsg(0));
    //printf("selfX: %d \n",selfX());
    //printf("selfY: %d \n",selfY());
    //printf("selfRadarX %d \n:",selfRadarX());
    //printf("selfRadarY: %d \n",selfRadarY());
    //printf("selfVelX: %d \n",selfVelX());
    //printf("selfVelY: %d \n",selfVelY());
    //printf("selfSpeed: %d \n",selfSpeed());
    //printf("lockHeadingDeg: %f \n",lockHeadingDeg());
    //printf("lockHeadingRad: %f \n",lockHeadingRad());
    //printf("selfLockDist: %d \n",selfLockDist());
    //printf("selfReload: %d \n",selfReload());
    //printf("selfID: %d \n",selfID());
    //printf("selfAlive: %d \n",selfAlive());
    //printf("selfTeam: %d \n",selfTeam());
    //printf("selfLives: %d \n",selfLives());
    //printf("selfTrackingRad: %f \n",selfTrackingRad());
    //printf("selfTrackingDeg: %f \n",selfTrackingDeg());
    //printf("selfHeadingDeg: %f \n",selfHeadingDeg());
    //printf("selfHeadingRad: %f \n",selfHeadingRad());
    //printf("hudName: %s \n",hudName());
    //printf("hudScore: %s \n",hudScore());
    //printf("hudTimeLeft: %f \n",hudTimeLeft());
    //printf("getTurnSpeed: %f \n",getTurnSpeed());
    //printf("getPower: %f \n",getPower());
    //printf("selfShield: %d \n",selfShield());
    //printf("selfName: %s \n",selfName());
    //printf("selfScore: %f \n",selfScore());
    //printf("closestRadarX: %d \n",closestRadarX());
    //printf("closestRadarY: %d \n",closestRadarY());
    //printf("closestItemX: %d \n",closestItemX());
    //printf("closestItemY: %d \n",closestItemY());
    //printf("closestShipId: %d \n",closestShipId());
    //printf("enemySpeedId: %f \n",enemySpeedId(closestShipId()));
    //printf("enemyTrackingRadId: %f \n",enemyTrackingRadId(closestShipId()));
    //printf("enemyTrackingDegId: %f \n",enemyTrackingDegId(closestShipId()));
    //printf("enemyReloadId: %d \n",enemyReloadId(closestShipId()));
    //printf("screenEnemyXId: %d \n",screenEnemyXId(closestShipId()));
    //printf("screenEnemyYId: %d \n",screenEnemyYId(closestShipId()));
    //printf("enemyHeadingDegId: %f \n",enemyHeadingDegId(closestShipId()));
    //printf("enemyHeadingRadId: %f \n",enemyHeadingRadId(closestShipId()));
    //printf("enemyShieldId: %d \n",enemyShieldId(closestShipId()));
    //printf("enemyLivesId: %d \n",enemyLivesId(closestShipId()));
    //printf("enemyNameId: %s \n",enemyNameId(closestShipId()));
    //printf("enemyScoreId: %f \n",enemyScoreId(closestShipId()));
    //printf("enemyTeamId: %d \n",enemyTeamId(closestShipId()));
    //printf("enemyDistanceId: %f \n",enemyDistanceId(closestShipId()));
    //printf("enemyDistance: %f \n",enemyDistance(0));
    //printf("enemySpeed: %f \n",enemySpeed(0));
    //printf("enemyReload: %d \n",enemyReload(0));
    //printf("enemyTrackingRad: %f \n",enemyTrackingRad(0));
    //printf("enemyTrackingDeg: %f \n",enemyTrackingDeg(0));
    //printf("screenEnemyX: %d \n",screenEnemyX(0));
    //printf("screenEnemyY: %d \n",screenEnemyY(0));
    //printf("enemyHeadingDeg:%f \n",enemyHeadingDeg(0));
    //printf("enemyHeadingRad: %f \n",enemyHeadingRad(0));
    //printf("enemyShield: %d \n",enemyShield(0));
    //printf("enemyLives: %d \n",enemyLives(0));
    //printf("enemyTeam: %d \n",enemyTeam(0));
    //printf("enemyName:%s \n" ,enemyName(0));
    //printf("enemyScore: %f \n",enemyScore(0));
    //printf("degToRad: %f \n",degToRad(180));
    //printf("radToDeg: %d \n",radToDeg(PI/2));
    //printf("angleDiff: %d \n",angleDiff(1,3));
    //printf("angleAdd: %d \n",angleAdd(1,3));
    //printf("wallFeeler: %d \n",wallFeeler(100,0,1,1));
    //printf("wallFeelerRad: %d \n",wallFeelerRad(100,0.0,1,1));
    //printf("wallBetween: %d \n",wallBetween(87,600,87,1000,1,1));
    //printf("shotAlert: %d \n",shotAlert(0));
    //printf("shotX: %d \n",shotX(0));
    //printf("shotY: %d \n",shotY(0));
    //printf("shotDist: %d \n",shotDist(0));
    //printf("shotVel: %d \n",shotVel(0));
    //printf("shotVelDir: %d \n",shotVelDir(0));
    //printf("aimdir: %d \n",aimdir(0));
    //printf("ballX: %d \n",ballX());
    //printf("ballY: %d \n",ballY());
    //printf("connectorX0: %d \n",connectorX0());
    //printf("connectorX1: %d \n",connectorX1());
    //printf("connectorY0: %d \n",connectorY0());
    //printf("connectorY1: %d \n",connectorY1());
    printf("Test Complete...yeah! \n");
  }
int main(int argc, char *argv[]) {
  return start(argc, argv);
}
