//Justin Anderson - May 2012
//Compile: javac TesterBot.java
//Run: java TesterBot
class TesterBot extends javaAI {
    @Override
    public void AI_loop() {
        turnLeft(1);
        //turnRight(1);
        //turn(20);
        //turnToDeg(270);
        //thrust(1);
        //setTurnSpeed(1);
        //setPower(1);
        //fasterTurnrate();
        //slowerTurnrate();
        //morePower();
        //lessPower();
        //fireShot();
        //fireMissile();
        //fireTorpedo();
        //fireHeat();
        //dropMine();
        //detachMine();
        //detonateMines();
        //fireLaser();
        //tankDetach();
        //cloak();
        //ecm();
        //transporter();
        //tractorBeam(1);
        //pressorBeam(1);
        //phasing();
        //shield();
        //emergencyShield();
        //hyperjump();
        //nextTank();
        //prevTank();
        //toggleAutopilot();
        //emergencyThrust();
        //deflector();
        //selectItem();
        //loseItem();
        //lockNext();
        //lockPrev();
        //lockClose();
        //lockNextClose();
        //loadLock1();
        //loadLock2();
        //loadLock3();
        //loadLock4();
        //toggleNuclear();
        //togglePower();
        //toggleVelocity();
        //toggleCluster();
        //toggleMini();
        //toggleSpread();
        //toggleLaser();
        //toggleImplosion();
        //toggleUserName();
        //loadModifiers1();
        //loadModifiers2();
        //loadModifiers3();
        //loadModifiers4();
        //clearModifiers();
        //connector(1);
        //dropBall();
        //refuel(1);
        //keyHome();
        //selfDestruct();
        //pauseAI();
        //swapSettings();
        //quitAI();
        //talkKey();
        //toggleCompass();
        //toggleShowMessage();
        //toggleShowItems();
        //repair();
        //reprogram();
        //talk("Hello");
	//System.out.println ("scanMsg:"+scanMsg(0));
        //System.out.println ("selfX:"+selfX());
        //System.out.println ("selfY:"+selfY());
        //System.out.println ("selfRadarX:"+selfRadarX());
        //System.out.println ("selfRadarY:"+selfRadarY());
        //System.out.println ("selfVelX:"+selfVelX());
        //System.out.println ("selfVelY:"+selfVelY());
        //System.out.println ("selfSpeed:"+selfSpeed());
        //System.out.println ("lockHeadingDeg:"+lockHeadingDeg());
        //System.out.println ("lockHeadingRad:"+lockHeadingRad());
        //System.out.println ("selfLockDist:"+selfLockDist());
        //System.out.println ("selfReload:"+selfReload());
        //System.out.println ("selfID:"+selfID());
        //System.out.println ("selfAlive:"+selfAlive());
        //System.out.println ("selfTeam:"+selfTeam());
        //System.out.println ("selfLives:"+selfLives());
        //System.out.println ("selfTrackingRad:"+selfTrackingRad());
        //System.out.println ("selfTrackingDeg:"+selfTrackingDeg());
        //System.out.println ("selfHeadingDeg:"+selfHeadingDeg());
        //System.out.println ("selfHeadingRad:"+selfHeadingRad());
        //System.out.println ("hudName:"+hudName());
        //System.out.println ("hudScore:"+hudScore());
        //System.out.println ("hudTimeLeft:"+hudTimeLeft());
        //System.out.println ("getTurnSpeed:"+getTurnSpeed());
        //System.out.println ("getPower:"+getPower());
        //System.out.println ("selfShield:"+selfShield());
        //System.out.println ("selfName:"+selfName());
        //System.out.println ("selfScore:"+selfScore());
        //System.out.println ("closestRadarX:"+closestRadarX());
        //System.out.println ("closestRadarY:"+closestRadarY());
        //System.out.println ("closestItemX:"+closestItemX());
        //System.out.println ("closestItemY:"+closestItemY());
        //System.out.println ("closestShipId:"+closestShipId());
        //System.out.println ("enemySpeedId:"+enemySpeedId(closestShipId()));
        //System.out.println ("enemyTrackingRadId:"+enemyTrackingRadId(closestShipId()));
        //System.out.println ("enemyTrackingDegId:"+enemyTrackingDegId(closestShipId()));
        //System.out.println ("enemyReloadId:"+enemyReloadId(closestShipId()));
        //System.out.println ("screenEnemyXId:"+screenEnemyXId(closestShipId()));
        //System.out.println ("screenEnemyYId:"+screenEnemyYId(closestShipId()));
        //System.out.println ("enemyHeadingDegId:"+enemyHeadingDegId(closestShipId()));
        //System.out.println ("enemyHeadingRadId:"+enemyHeadingRadId(closestShipId()));
        //System.out.println ("enemyShieldId:"+enemyShieldId(closestShipId()));
        //System.out.println ("enemyLivesId:"+enemyLivesId(closestShipId()));
        //System.out.println ("enemyNameId:"+enemyNameId(closestShipId()));
        //System.out.println ("enemyScoreId:"+enemyScoreId(closestShipId()));
        //System.out.println ("enemyTeamId:"+enemyTeamId(closestShipId()));
        //System.out.println ("enemyDistanceId:"+enemyDistanceId(closestShipId()));
        //System.out.println ("enemyDistance:"+enemyDistance(0));
        //System.out.println ("enemySpeed:"+enemySpeed(0));
        //System.out.println ("enemyReload:"+enemyReload(0));
        //System.out.println ("enemyTrackingRad:"+enemyTrackingRad(0));
        //System.out.println ("enemyTrackingDeg:"+enemyTrackingDeg(0));
        //System.out.println ("screenEnemyX:"+screenEnemyX(0));
        //System.out.println ("screenEnemyY:"+screenEnemyY(0));
        //System.out.println ("enemyHeadingDeg:"+enemyHeadingDeg(0));
        //System.out.println ("enemyHeadingRad:"+enemyHeadingRad(0));
        //System.out.println ("enemyShield:"+enemyShield(0));
        //System.out.println ("enemyLives:"+enemyLives(0));
        //System.out.println ("enemyTeam:"+enemyTeam(0));
        //System.out.println ("enemyName:"+enemyName(0));
        //System.out.println ("enemyScore:"+enemyScore(0));
        //System.out.println ("degToRad:"+degToRad(180));
        //System.out.println ("radToDeg:"+radToDeg(3.1415926536 /2));
        //System.out.println ("angleDiff:"+angleDiff(1,3));
        //System.out.println ("angleAdd:"+angleAdd(1,3));
        //System.out.println ("wallFeeler:"+wallFeeler(100,0,1,1));
        //System.out.println ("wallFeelerRad:"+wallFeelerRad(100,0.0,1,1));
        //System.out.println ("wallBetween:"+wallBetween(87,600,87,1000,1,1));
        //System.out.println ("angleAdd:"+angleAdd(1,3));
        //System.out.println ("shotAlert:"+shotAlert(0));
        //System.out.println ("shotX:"+shotX(0));
        //System.out.println ("shotY:"+shotY(0));
        //System.out.println ("shotDist:"+shotDist(0));
        //System.out.println ("shotVel:"+shotVel(0));
        //System.out.println ("shotVelDir:"+shotVelDir(0));
        //System.out.println ("aimdir:"+aimdir(0));
	//System.out.println ("ballX:"+ballX());
	//System.out.println ("ballY:"+ballY());
	//System.out.println ("connectorX0:"+connectorX0());
	//System.out.println ("connectorX1:"+connectorX1());
	//System.out.println ("connectorY0:"+connectorY0());
	//System.out.println ("connectorY1:"+connectorY1());
        System.out.println("Test Complete...yeah!");
}
        public TesterBot(String args[]) {
                super(args);
        }
        public static void main(String args[]) {
                String[] new_args = {"-name","Tester Bot"};
                TesterBot testerbot = new TesterBot(new_args);
        }
}

